"""Item and location name groups, for hints and YAML options such as start_inventory.

Location groups and the one- and two-handed weapon split come from Darvitz's unofficial 0.8.16
(github.com/Darvitz/Archipelago-Crystal), with two fixes: a location renamed since, and a missing
comma that merged two Reverse Caverns locations into one name. Type-based item groups are built from
Items.py so they stay complete; Darvitz's 13-relic "Relic" group is kept as "Power relic".
"""
from typing import Dict, Set

from .Items import items


def _of_type(*types: str) -> Set[str]:
    return {name for name, data in items.items() if data["type"] in types}


ITEM_GROUPS: Dict[str, Set[str]] = {
    "Relic": _of_type("RELIC"),
    "Power up": _of_type("POWERUP"),
    "Weapon": _of_type("WEAPON1", "WEAPON2"),
    "Shield": _of_type("SHIELD"),
    "Armor": _of_type("ARMOR"),
    "Helmet": _of_type("HELMET"),
    "Cloak": _of_type("CLOAK"),
    "Accessory": _of_type("ACCESSORY"),
    "Consumable": _of_type("USABLE"),
    "Vlad relic": {"Heart of vlad", "Tooth of vlad", "Rib of vlad", "Ring of vlad", "Eye of vlad"},
    "Familiar card": {"Bat card", "Ghost card", "Faerie card", "Demon card", "Sword card"},
    'Power relic': {
        'Cube of zoe',
        'Echo of bat',
        'Fire of bat',
        'Force of echo',
        'Form of mist',
        'Gas cloud',
        'Gravity boots',
        'Power of mist',
        'Power of wolf',
        'Skill of wolf',
        'Soul of bat',
        'Soul of wolf',
        'Spirit orb',
    },
    'Weapon 1H': {
        'Alucard sword',
        'Alucart sword',
        'Badelaire',
        'Basilard',
        'Bekatowa',
        'Blue knuckles',
        'Broadsword',
        'Chakram',
        'Combat knife',
        'Crissaegrim',
        'Cutlass',
        'Damascus sword',
        'Dark blade',
        'Estoc',
        'Falchion',
        'Firebrand',
        'Fist of tulkas',
        'Gladius',
        'Harper',
        'Heaven sword',
        'Holbein dagger',
        'Holy rod',
        'Holy sword',
        'Hunter sword',
        'Icebrand',
        'Iron fist',
        'Jewel knuckles',
        'Jewel sword',
        'Katana',
        'Knuckle duster',
        'Luminus',
        'Mablung sword',
        'Mace',
        'Marsil',
        'Moon rod',
        'Namakura',
        'Nunchaku',
        'Obsidian sword',
        'Rapier',
        'Red rust',
        'Saber',
        'Scimitar',
        'Shield rod',
        'Short sword',
        'Shotel',
        'Star flail',
        'Stone sword',
        'Sword familiar',
        'Sword of dawn',
        'Takemitsu',
        'Talwar',
        'Terminus est',
        'Thunderbrand',
        'Tyrfing',
        'Were bane',
    },
    'Weapon 2H': {
        'Bastard sword',
        'Claymore',
        'Flamberge',
        'Gram',
        'Great sword',
        'Gurthang',
        'Masamune',
        'Mormegil',
        'Morningstar',
        'Mourneblade',
        'Muramasa',
        'Osafune katana',
        'Runesword',
        'Sword of hador',
        'Vorpal blade',
        'Yasutsuna',
        'Zwei hander',
    },
}

LOCATION_GROUPS: Dict[str, Set[str]] = {
    'Abandoned Mine': {
        'Abandoned Mine - Bottom Descend Item 1',
        'Abandoned Mine - Bottom Descend Item 2',
        'Abandoned Mine - Cerberus item',
        'Abandoned Mine - Middle Descend Left Room',
        'Abandoned Mine Bottom - Left Item',
        'Abandoned Mine Bottom - Right Item',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 1',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 2',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 3',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 4',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 5',
        'Abandoned Mine Demon Side - Behind Breakable Wall Item 6',
        'Abandoned Mine Demon Side - Item on Breakable Wall',
        'Abandoned Mine Demon Side - Item on the Floor',
    },
    'Alchemy Lab.': {
        'Alchemy Lab. - Flame Near Spike Switch',
        'Alchemy Lab. - Flame on Table Middle Way Up',
        'Alchemy Lab. - Globe After Spike Puzzle',
        'Alchemy Lab. - Globe by the Bottom Entrance',
        'Alchemy Lab. - Globe in Attic With Powerup Tanks',
        'Alchemy Lab. - Globe in Big Room With Axe Lord and Spittle Bone',
        'Alchemy Lab. - Globe in Hidden Room Behind Breakable Wall',
        'Alchemy Lab. - Globe in Upper-left Room of Slogra and Gaibon',
        'Alchemy Lab. - Globe on Middle Elevator Shaft Room',
        'Alchemy Lab. - Item by Cannon',
        'Alchemy Lab. - Slogra and Gaibon item',
        'Alchemy Lab. - Tank in Hidden Basement on Breakable Floor',
    },
    'Anti-Chapel': {
        'Anti-Chapel - After Spiked Tunnel',
        'Anti-Chapel - Next to Upper Save Point',
        'Anti-Chapel Stairs - Bottom Yellow Vase',
        'Anti-Chapel Stairs - Red Vase Alcove 1',
        'Anti-Chapel Stairs - Red Vase Alcove 2',
        'Anti-Chapel Stairs - Red Vase Alcove 3',
        'Anti-Chapel Stairs - Red Vase Alcove 4',
        'Anti-Chapel Stairs - Red Vase Alcove 5',
        'Anti-Chapel Stairs - Red Vase Alcove 6',
        'Anti-Chapel Stairs - Red Vase at Top',
        'Anti-Chapel Tower 1 - Bottom Item',
        'Anti-Chapel Tower 1 - Red Vase',
        'Anti-Chapel Tower 2 - Bottom Item',
        'Anti-Chapel Tower 3  - Bottom Item',
        'Anti-Chapel Tower 3 - Red Vase',
        'Anti-Chapel Tower 3 - Yellow Vase',
    },
    'Black Marble Gallery': {
        'Black Marble Gallery - Ascend to Entrance Item on Floor 1',
        'Black Marble Gallery - Ascend to Entrance Item on Floor 2',
        'Black Marble Gallery - Behind Magic Blue Door',
        'Black Marble Gallery - Corridor to Entrance Item on Spike Trap',
        'Black Marble Gallery - Hole on the Ceiling',
        'Black Marble Gallery - Item Inside the Clock',
        'Black Marble Gallery - Left Clock First Room Item on Left',
        'Black Marble Gallery - Left Clock First Room Item on Right',
        'Black Marble Gallery - Left Clock Second Room Item on Left',
        'Black Marble Gallery - Left Clock Second Room Item on Right',
        'Black Marble Gallery - Middle Clock Left Item',
        'Black Marble Gallery - Middle Clock Right Item',
    },
    'Boss Items': {
        'Abandoned Mine - Cerberus item',
        'Alchemy Lab. - Slogra and Gaibon item',
        'Catacombs - Granfaloon item',
        'Clock Tower - Karasuman item',
        'Colosseum - Minotaur & Werewolf item',
        'Floating Catacombs - Galamoth item',
        'Long Library - Lesser Demon item',
        'Necromancy Lab. - Beezelbub item',
        "Olrox's Quarters - Olrox item",
        'Outer Wall - Doppleganger 10 item',
        'Reverse Caverns - Doppleganger 40 item',
        'Reverse Colosseum - Trio item',
        'Royal Chapel - Hippogryph item',
        'Underground Caverns - Scylla item',
    },
    'Castle Keep': {
        'Castle Keep - Attic by Elevator Surround by Torches',
        'Castle Keep - Hidden Stair Room Left Statue 1',
        'Castle Keep - Hidden Stair Room Left Statue 2',
        'Castle Keep - Hidden Stair Room Left Yellow Vase 1',
        'Castle Keep - Hidden Stair Room Left Yellow Vase 2',
        'Castle Keep - Hidden Stair Room Right Statue 1',
        'Castle Keep - Hidden Stair Room Right Statue 2',
        'Castle Keep - Hidden Stair Room Right Yellow Vase 1',
        'Castle Keep - Hidden Stair Room Right Yellow Vase 2',
        'Castle Keep - Open Area Bottom Left Floor Item',
        'Castle Keep - Open Area Bottom Left on Ledge',
        'Castle Keep - Open Area Bottom Left on Ledge Breakable Wall',
        'Castle Keep - Open Area Top Left Alcove',
        'Castle Keep - Open Area Top Left Alcove Breakable Wall',
        'Castle Keep - Open Area Top Right Room Item 1',
        'Castle Keep - Open Area Top Right Room Item 2',
        'Castle Keep - Open Area Top Right Room Item 3',
        'Castle Keep - Open Area Top Right Room Item 4',
        'Castle Keep - Open Area Top Right Room Item 5',
        'Castle Keep - Red Vase Before Richter',
        'Castle Keep - Top Right Room by Dual Moving Platforms',
    },
    'Catacombs': {
        'Catacombs - Granfaloon item',
        'Catacombs After Dark Spiked Area - Bottom Left Breakable',
        'Catacombs After Dark Spiked Area - Bottom Left Item',
        'Catacombs After Dark Spiked Area - Bottom Right Item',
        'Catacombs After Dark Spiked Area - Red Vase 1',
        'Catacombs After Dark Spiked Area - Red Vase 2',
        'Catacombs After Dark Spiked Area - Red Vase 3',
        'Catacombs After Dark Spiked Area - Red Vase 4',
        'Catacombs Bottom - Above Discus Lord Breakable Wall Room',
        'Catacombs Bottom - Above Discus Lord Red Vase 1',
        'Catacombs Bottom - Above Discus Lord Red Vase 2',
        'Catacombs Bottom - After Crypt Left Item',
        'Catacombs Bottom - After Crypt Right Item',
        'Catacombs Bottom - After Granfaloon',
        'Catacombs Bottom - After Save Point',
        'Catacombs Bottom - Sarcophagus 1',
        'Catacombs Bottom - Sarcophagus 2',
        'Catacombs Bottom - Sarcophagus 3',
        'Catacombs Bottom - Sarcophagus 4',
        'Catacombs Upper - After Save Point',
        'Catacombs Upper - After Save Point Breakable Wall',
    },
    'Cave': {
        'Cave - Death Item',
        'Cave - Middle Ascend Right Item',
        'Cave - Upper Ascend Item 1',
        'Cave - Upper Ascend Item 2',
        'Cave - Upper Right Room Left Item(Shared with Demon Side)',
        'Cave - Upper Right Room Right Item',
        'Cave Demon Side - Breakable Wall Room Left Item',
        'Cave Demon Side - Breakable Wall Room Right Item',
    },
    'Clock Tower': {
        'Clock Tower - After Rotating Gears Behind Breakable Wall',
        'Clock Tower - Before Karasuman Breakable Wall Item 1',
        'Clock Tower - Before Karasuman Breakable Wall Item 2',
        'Clock Tower - Before Karasuman Breakable Wall Item 3',
        'Clock Tower - Behind Breakable Wall Close to Bronze Statue',
        'Clock Tower - Bellow Broken Bridge Item 1',
        'Clock Tower - Bellow Broken Bridge Item 2',
        'Clock Tower - Gears Puzzle Room Breakable Wall Room Left Item',
        'Clock Tower - Gears Puzzle Room Breakable Wall Room Right Item',
        'Clock Tower - Karasuman item',
        'Clock Tower - On Top of Column Item 1',
        'Clock Tower - On Top of Column Item 2',
        'Clock Tower - On Top of Column Item 3',
        'Clock Tower - Rotating Gears Puzzle Room Item 1',
        'Clock Tower - Rotating Gears Puzzle Room Item 2',
        'Clock Tower - Rotating Gears Puzzle Room Item 3',
        'Clock Tower - Top Right Room in Open Area',
    },
    'Colosseum': {
        'Colosseum - Minotaur & Werewolf item',
        'Colosseum First Part - Before Minotaurus & Werewolf',
        'Colosseum First Part - Bottom Left Room',
        'Colosseum First Part - Bottom Right Room',
        'Colosseum First Part - Next to Royal Chapel Passage',
        'Colosseum Junction Tunnel - Attic',
        'Colosseum Second Part - Behind Mist Crate',
        'Colosseum Second Part - Bottom Left Room',
        'Colosseum Second Part - Bottom Right Room',
    },
    "Death Wing's Lair": {
        "Death Wing's Lair - After Akmodan II",
        "Death Wing's Lair - Akmodan II Item",
        "Death Wing's Lair - Attic Before Akmodan II",
        "Death Wing's Lair - Red Vase Next to Path to Courtyard",
        "Death Wing's Lair Courtyard - Top Left Room",
        "Death Wing's Lair Main Area - Room Behind Breakable Wall Left Red Vase",
        "Death Wing's Lair Main Area - Room Behind Breakable Wall Middle Red Vase",
        "Death Wing's Lair Main Area - Room Behind Breakable Wall Right Red Vase",
        "Death Wing's Lair Path to Anti-Chapel - Bellow Wooden Pedestal",
        "Death Wing's Lair Path to Anti-Chapel - Breakable Floor Room",
        "Death Wing's Lair Upper Part - Bottom Red Vase on Shaft",
        "Death Wing's Lair Upper Part - Middle Red Vase on Shaft",
        "Death Wing's Lair Upper Part - Top Red Vase on Shaft",
    },
    'Enemysanity': {
        'Enemysanity - Akmodan II',
        'Enemysanity - Archer',
        'Enemysanity - Armor lord',
        'Enemysanity - Axe knight',
        'Enemysanity - Axe knight(armored)',
        'Enemysanity - Azaghal',
        'Enemysanity - Ballon pod',
        'Enemysanity - Bat',
        'Enemysanity - Beezelbub',
        'Enemysanity - Bitterfly',
        'Enemysanity - Black crow',
        'Enemysanity - Black panther',
        'Enemysanity - Blade',
        'Enemysanity - Blade master',
        'Enemysanity - Blade soldier',
        'Enemysanity - Blood skeleton',
        'Enemysanity - Bloody zombie',
        'Enemysanity - Blue raven',
        'Enemysanity - Blue venus weed',
        'Enemysanity - Bomb knight',
        'Enemysanity - Bone archer',
        'Enemysanity - Bone ark',
        'Enemysanity - Bone halberd',
        'Enemysanity - Bone musket',
        'Enemysanity - Bone pillar',
        'Enemysanity - Bone scimitar',
        'Enemysanity - Cave troll',
        'Enemysanity - Cerberos',
        'Enemysanity - Cloaked knight',
        'Enemysanity - Corner guard',
        'Enemysanity - Corpseweed',
        'Enemysanity - Ctulhu',
        'Enemysanity - Dark octopus',
        'Enemysanity - Darkwing bat',
        'Enemysanity - Death',
        'Enemysanity - Dhuron',
        'Enemysanity - Diplocephalus',
        'Enemysanity - Discus lord',
        'Enemysanity - Dodo bird',
        'Enemysanity - Doppleganger10',
        'Enemysanity - Doppleganger40',
        'Enemysanity - Dragon rider',
        'Enemysanity - Ectoplasm',
        'Enemysanity - Fake Grant',
        'Enemysanity - Fake Sipha',
        'Enemysanity - Fake Trevor',
        'Enemysanity - Fire demon',
        'Enemysanity - Fire warg',
        'Enemysanity - Fishhead',
        'Enemysanity - Flail guard',
        'Enemysanity - Flea armor',
        'Enemysanity - Flea man',
        'Enemysanity - Flea rider',
        'Enemysanity - Flying zombie',
        'Enemysanity - Frog',
        'Enemysanity - Frozen half',
        'Enemysanity - Frozen shade',
        'Enemysanity - Gaibon',
        'Enemysanity - Galamoth',
        'Enemysanity - Ghost',
        'Enemysanity - Ghost dancer',
        'Enemysanity - Gorgon',
        'Enemysanity - Granfaloon',
        'Enemysanity - Grave keeper',
        'Enemysanity - Gremlin',
        'Enemysanity - Guardian',
        'Enemysanity - Gurkha',
        'Enemysanity - Hammer',
        'Enemysanity - Harpy',
        'Enemysanity - Hellfire beast',
        'Enemysanity - Hippogryph',
        'Enemysanity - Hunting girl',
        'Enemysanity - Imp',
        "Enemysanity - Jack O'bones",
        'Enemysanity - Karasuman',
        'Enemysanity - Killer fish',
        'Enemysanity - Large slime',
        'Enemysanity - Lesser demon',
        'Enemysanity - Lion',
        'Enemysanity - Lossoth',
        'Enemysanity - Magic tome',
        'Enemysanity - Malachi',
        'Enemysanity - Marionette',
        'Enemysanity - Medusa',
        'Enemysanity - Medusa head',
        'Enemysanity - Medusa head(yellow)',
        'Enemysanity - Merman',
        'Enemysanity - Merman(red)',
        'Enemysanity - Minotaur',
        'Enemysanity - Minotaurus',
        'Enemysanity - Nova skeleton',
        'Enemysanity - Olrox',
        'Enemysanity - Orobourous',
        'Enemysanity - Ouija table',
        'Enemysanity - Owl',
        'Enemysanity - Owl knight',
        'Enemysanity - Paranthropus',
        'Enemysanity - Phantom skull',
        'Enemysanity - Plate lord',
        'Enemysanity - Rock knight',
        'Enemysanity - Salem witch',
        'Enemysanity - Salome',
        'Enemysanity - Scarecrow',
        'Enemysanity - Schmoo',
        'Enemysanity - Scylla',
        'Enemysanity - Scylla wyrm',
        'Enemysanity - Skelerang',
        'Enemysanity - Skeleton',
        'Enemysanity - Skeleton ape',
        'Enemysanity - Skull lord',
        'Enemysanity - Slime',
        'Enemysanity - Slinger',
        'Enemysanity - Slogra',
        'Enemysanity - Sniper of goth',
        'Enemysanity - Spear guard',
        'Enemysanity - Spectral sword',
        'Enemysanity - Spectral sword(shields)',
        'Enemysanity - Spectral sword(swords)',
        'Enemysanity - Spellbook',
        'Enemysanity - Spittle bone',
        'Enemysanity - Stone rose',
        'Enemysanity - Stone skull',
        'Enemysanity - Succubus',
        'Enemysanity - Sword lord',
        'Enemysanity - The creature',
        'Enemysanity - Thornweed',
        'Enemysanity - Tin man',
        'Enemysanity - Toad',
        'Enemysanity - Tombstone',
        'Enemysanity - Valhalla knight',
        'Enemysanity - Vandal sword',
        'Enemysanity - Venus weed',
        'Enemysanity - Warg',
        'Enemysanity - Warg rider',
        'Enemysanity - Wereskeleton',
        'Enemysanity - Werewolf',
        'Enemysanity - Werewolf(reverse)',
        'Enemysanity - White dragon',
        'Enemysanity - Winged guard',
        'Enemysanity - Yorick',
        'Enemysanity - Zombie',
    },
    'Entrance': {
        'Entrance - Above First Encounter With Death',
        'Entrance - Attic Above Mermans',
        'Entrance - Attic Near Start Gate Left item',
        'Entrance - Attic Near Start Gate Right item',
        'Entrance - Behind Stone Wall in Cube of Zoe Room',
        'Entrance - Breakable Ledge Before Death',
        'Entrance - Breakable Wall Above Merman',
        'Entrance - By Underground Caverns Bottom Exit',
        'Entrance - Castle Entrance Teleport Exit',
        'Entrance - Pedestal in Cube of Zoe Room',
        'Entrance - Right Alcove in Cube of Zoe Room',
        'Entrance - Wolf/Bat Secret Room Left Item',
        'Entrance - Wolf/Bat Secret Room Right Item',
    },
    'Floating Catacombs': {
        'Floating Catacombs - Galamoth item',
        'Floating Catacombs After Spike Tunnel - Bottom Left Vase',
        'Floating Catacombs After Spike Tunnel - Bottom Right Vase',
        'Floating Catacombs After Spike Tunnel - Deep Left Item',
        'Floating Catacombs After Spike Tunnel - Deep Right Breakable Wall Item',
        'Floating Catacombs After Spike Tunnel - Deep Right Item',
        'Floating Catacombs After Spike Tunnel - Top Left Vase',
        'Floating Catacombs After Spike Tunnel - Top Right Vase',
        'Floating Catacombs Bottom - After Save Point Breakable Wall',
        'Floating Catacombs Bottom - After Save Point Item',
        'Floating Catacombs Upper - After Crypt Breakable Wall Room',
        'Floating Catacombs Upper - After Crypt Cave Bottom Red Vase',
        'Floating Catacombs Upper - After Crypt Cave Upper Red Vase',
        'Floating Catacombs Upper - After Galamoth Deeper Room Left Item',
        'Floating Catacombs Upper - After Galamoth Deeper Room Right Item',
        'Floating Catacombs Upper - After Galamoth Left Item',
        'Floating Catacombs Upper - After Galamoth Right Item',
        'Floating Catacombs Upper - Before Galamoth Save Point',
        'Floating Catacombs Upper - Start of Crypt Left Item',
        'Floating Catacombs Upper - Start of Crypt Right Item',
    },
    'Forbidden Library': {
        'Forbidden Library - Inner Study Left Statue',
        'Forbidden Library - Inner Study Red Vase',
        'Forbidden Library - Inner Study Right Statue',
        'Forbidden Library Inner Part - Behind Mist Crate',
        'Forbidden Library Inner Part - Bottom Left Room Behind Bookshelf',
        'Forbidden Library Inner Part - Bottom Left Room Green Candle',
        'Forbidden Library Main Area - Bottom Right Room Left Item',
        'Forbidden Library Main Area - Bottom Right Room Middle Item',
        'Forbidden Library Main Area - Bottom Right Room Right Item',
    },
    'Long Library': {
        'Long Library - Deeper Library Behind Bookshelf Item 1',
        'Long Library - Deeper Library Behind Bookshelf Item 2',
        'Long Library - Deeper Library Behind Mist Crate',
        'Long Library - Deeper Library Lower Part Red Vase',
        'Long Library - Deeper Library Lower Part Statue 1',
        'Long Library - Deeper Library Lower Part Statue 2',
        'Long Library - Deeper Library Upper Part Flame on Table',
        'Long Library - Item Bellow Librarian',
        'Long Library - Lesser Demon item',
        'Long Library - Librarian Shop Item',
        'Long Library - Top Left Room Item 1',
        'Long Library - Top Left Room Item 2',
        'Long Library - Top Left Room Item 3',
        'Long Library - Top Right Floor',
    },
    'Marble Gallery': {
        'Marble Gallery - Bellow Red Trap Door Left Item',
        'Marble Gallery - Bellow Red Trap Door Right Item',
        'Marble Gallery - Descend to Entrance Item 1',
        'Marble Gallery - Descend to Entrance Item 2',
        'Marble Gallery - Descend to Entrance Item 3',
        'Marble Gallery - Inside Clock Left Item',
        'Marble Gallery - Inside Clock Right Item',
        'Marble Gallery - Item Given by Maria',
        "Marble Gallery - Left Clock Before Olrox's Quarter",
        'Marble Gallery - Middle clock Left Item 1',
        'Marble Gallery - Middle clock Left Item 2',
        'Marble Gallery - Middle clock Left Item 3',
        'Marble Gallery - Middle clock Right Item',
        'Marble Gallery - Right Clock Item 1',
        'Marble Gallery - Right Clock Item 2',
        'Marble Gallery - Right Clock Item 3',
        'Marble Gallery - Right Clock Item 4',
    },
    'Necromancy Lab.': {
        'Necromancy Lab. - Beezelbub item',
        'Necromancy Lab. - Blue Flame in Room With Lesser and Fire Demons',
        'Necromancy Lab. - Bottom Left Room From Beezelbub',
        'Necromancy Lab. - Bottom Room From Spike Traps',
        'Necromancy Lab. - Breakable Ceil on Tunnel Right of Elevator Shaft',
        'Necromancy Lab. - Breakable Wall on Tunnel Right of Elevator Shaft',
        'Necromancy Lab. - Globe in Bitterfly Room',
        'Necromancy Lab. - Globe in the Room With Lesser Demons and Ctulhu',
        'Necromancy Lab. - Hole in Room With Lesser and Fire Demons',
        'Necromancy Lab. - Middle Room on Elevator Shaft',
    },
    "Olrox's Quarters": {
        "Olrox's Quarters - After Olrox",
        "Olrox's Quarters - Hole Before Olrox",
        "Olrox's Quarters - Olrox item",
        "Olrox's Quarters Courtyard - Right Room",
        "Olrox's Quarters Lower Part - Room Behind Breakable Wall Vase 1",
        "Olrox's Quarters Lower Part - Room Behind Breakable Wall Vase 2",
        "Olrox's Quarters Lower Part - Room Behind Breakable Wall Vase 3",
        "Olrox's Quarters Path to Royal Chapel - Hidden Attic",
        "Olrox's Quarters Path to Royal Chapel - On Wooden Display",
        "Olrox's Quarters Upper Part - Ascend Shaft Red Vase 1",
        "Olrox's Quarters Upper Part - Ascend Shaft Red Vase 2",
        "Olrox's Quarters Upper Part - Ascend Shaft Red Vase 3",
        "Olrox's Quarters Upper Part - Ledge Before Drop to Courtyard",
    },
    'Outer Wall': {
        'Outer Wall - Breakable Wall in Room Behind Armor Lord',
        'Outer Wall - Doppleganger 10 item',
        'Outer Wall - Inside of Elevator',
        'Outer Wall - Item 1 Behind Mist Grate',
        'Outer Wall - Item 2 Behind Mist Grate',
        'Outer Wall - Item After Doppleganger 10',
        'Outer Wall - Red Vase After Doppleganger 10',
        'Outer Wall - Red Vase Near Elevator Switch',
        'Outer Wall - Red Vase Near Marble Gallery Door',
        'Outer Wall - Yellow Vase on High Ledge',
    },
    'Pieces of Vlad': {
        'Cave - Death Item',
        'Creature Kill Item',
        "Death Wing's Lair - Akmodan II Item",
        'Medusa Kill Item',
        'Reverse Clock Tower - Darkwing Bat Item',
    },
    'R. Castle Keep': {
        'R. Castle Keep - Bellow Save Point',
        'R. Castle Keep - Bellow Stairs Left Statue 1',
        'R. Castle Keep - Bellow Stairs Left Statue 2',
        'R. Castle Keep - Bellow Stairs Left Yellow Vase 1',
        'R. Castle Keep - Bellow Stairs Left Yellow Vase 2',
        'R. Castle Keep - Bellow Stairs Right Statue 1',
        'R. Castle Keep - Bellow Stairs Right Statue 2',
        'R. Castle Keep - Bellow Stairs Right Yellow Vase 1',
        'R. Castle Keep - Bellow Stairs Right Yellow Vase 2',
        'R. Castle Keep - Bottom Left Room on Dual Elevator Area',
        'R. Castle Keep - Open Area Bottom Left Underpass Breakable Wall',
        'R. Castle Keep - Open Area Bottom Right Room Item 1',
        'R. Castle Keep - Open Area Bottom Right Room Item 2',
        'R. Castle Keep - Open Area Bottom Right Room Item 3',
        'R. Castle Keep - Open Area Bottom Right Room Item 4',
        'R. Castle Keep - Open Area Bottom Right Room Window Item',
        'R. Castle Keep - Open Area Top Right Breakable Wall',
        'R. Castle Keep - Open Area Top Right Ledge',
        'R. Castle Keep - Red Vase After Entering',
    },
    'Reverse Caverns': {
        'Reverse Caverns - Doppleganger 40 item',
        'Reverse Caverns Bottom - Alcove Near Water Leak',
        'Reverse Caverns Bottom - Item on Air Pocket',
        'Reverse Caverns Bottom - Near Stairs Hole',
        'Reverse Caverns Bottom - Red Vase Near Exit',
        'Reverse Caverns Bottom - Underwater Bottom Item',
        'Reverse Caverns Bottom - Underwater Stream',
        'Reverse Caverns Bottom - Underwater Top Item',
        'Reverse Caverns Doppleganger - Bottom Area Left Red Vase',
        'Reverse Caverns Doppleganger - Bottom Area Right Room',
        'Reverse Caverns Doppleganger - Item on Alcove',
        'Reverse Caverns Ice Area - At End',
        'Reverse Caverns Ice Area - Inside Cave',
        'Reverse Caverns Ice Area - Underwater Alcove Item',
        'Reverse Caverns Stairs - Bottom Item',
        'Reverse Caverns Stairs - Bottom Item Behind Breakable Wall',
        'Reverse Caverns Stairs - Middle Room',
        'Reverse Caverns Succubus Side - Bottom Left Red Vase',
        'Reverse Caverns Succubus Side - First Red Vase',
        'Reverse Caverns Succubus Side - Middle Left Red Vase',
        'Reverse Caverns Succubus Side - Middle Right Red Vase',
        'Reverse Caverns Succubus Side - Top Left Red Vase',
        'Reverse Caverns Succubus Side - Top Right Red Vase',
        'Reverse Caverns Upper - End of Cavern',
        'Reverse Caverns Upper - Near Exit',
        'Reverse Caverns Waterfall - Alcove 1',
        'Reverse Caverns Waterfall - Alcove 2',
        'Reverse Caverns Waterfall - Behind Waterfall Room',
        'Reverse Caverns Waterfall - Bottom Right Room',
    },
    'Reverse Clock Tower': {
        'Reverse Clock Tower - Behind Breakable Wall Next to Bronze Statue',
        'Reverse Clock Tower - Breakable Wall Item on Brackets',
        'Reverse Clock Tower - Darkwing Bat Item',
        'Reverse Clock Tower - Near Darkwing Bat Left Breakable Wall',
        'Reverse Clock Tower - Near Darkwing Bat Middle Breakable Wall',
        'Reverse Clock Tower - Near Darkwing Bat Right Breakable Wall',
        'Reverse Clock Tower Medusa Area - Gears Puzzle Room Left Item',
        'Reverse Clock Tower Medusa Area - Gears Puzzle Room Middle Item',
        'Reverse Clock Tower Medusa Area - Gears Puzzle Room Right Item',
        'Reverse Clock Tower Medusa Area - Room Behind Bottom Left Breakable Wall Left Item',
        'Reverse Clock Tower Medusa Area - Room Behind Bottom Left Breakable Wall Right Item',
        'Reverse Clock Tower Open Area - Above Stone Bridge Left Item',
        'Reverse Clock Tower Open Area - Above Stone Bridge Right Item',
        'Reverse Clock Tower Open Area - Bottom Left Room',
        'Reverse Clock Tower Open Area - Left Column',
        'Reverse Clock Tower Open Area - Middle Column',
        'Reverse Clock Tower Open Area - Right Column',
    },
    'Reverse Colosseum': {
        'Reverse Colosseum - Trio item',
        'Reverse Colosseum Junction Tunnel - Breakable Floor Room',
        'Reverse Colosseum Left Part - Left Item on Floor',
        'Reverse Colosseum Left Part - Middle Item on Floor',
        'Reverse Colosseum Left Part - Right Item on Floor',
        'Reverse Colosseum Left Part - Top Left Room',
        'Reverse Colosseum Left Part - Top Right Room',
        'Reverse Colosseum Right Part - Top Left Room',
        'Reverse Colosseum Right Part - Top Right Room',
    },
    'Reverse Entrance': {
        'Reverse Entrance - Bellow Stone Pedestal',
        'Reverse Entrance - Breakable Big Rock in Main Corridor',
        'Reverse Entrance - Breakable Ledge on Main Corridor',
        'Reverse Entrance - Hole in Main Corridor Back Item',
        'Reverse Entrance - Main Gate Bottom Left Item',
        'Reverse Entrance - Main Gate Bottom Right Item',
        'Reverse Entrance - Middle Room in Open Area Before Main Corridor',
        'Reverse Entrance - Room by Nova Skeleton on the Ledge',
        'Reverse Entrance - Wolf/Bat Secret Room Left Item',
        'Reverse Entrance - Wolf/Bat Secret Room Middle Item',
        'Reverse Entrance - Wolf/Bat Secret Room Right Item',
    },
    'Reverse Outer Wall': {
        'Reverse Outer Wall - Bottom Red Vase Near Elevator Machinery',
        'Reverse Outer Wall - Breakable Wall on Room Bellow Mist Crate',
        'Reverse Outer Wall - Item at the Top',
        'Reverse Outer Wall - Item on the Floor Near Creature',
        'Reverse Outer Wall - Mist Crate Room Left Item',
        'Reverse Outer Wall - Mist Crate Room Right Item',
        'Reverse Outer Wall - Red Vase Near Creature',
        'Reverse Outer Wall - Red Vase Near Door to BMG',
        'Reverse Outer Wall - Yellow Vase on Alcove Near Creature',
    },
    'Royal Chapel': {
        'Royal Chapel - Hippogryph item',
        'Royal Chapel - Inner Chapel Doorway Roof',
        'Royal Chapel - Item Behind Maria',
        'Royal Chapel Stairs - Bottom Red Vase',
        'Royal Chapel Stairs - Red Vase on Alcove 1',
        'Royal Chapel Stairs - Red Vase on Alcove 2',
        'Royal Chapel Stairs - Red Vase on Alcove 3',
        'Royal Chapel Stairs - Red Vase on Alcove 4',
        'Royal Chapel Stairs - Red Vase on Alcove 5',
        'Royal Chapel Stairs - Red Vase on Alcove 6',
        'Royal Chapel Stairs - Upper Alcove',
        'Royal Chapel Tower 1 - Red Vase',
        'Royal Chapel Tower 1 - Top Item',
        'Royal Chapel Tower 1 - Yellow Vase',
        'Royal Chapel Tower 2 - Top Item',
        'Royal Chapel Tower 3 - Red Vase',
        'Royal Chapel Tower 3 - Top Item',
    },
    'Underground Caverns': {
        'Underground Caverns - After Ferryman',
        'Underground Caverns - Air Pocket Item',
        'Underground Caverns - Alcove Behind Waterfall',
        'Underground Caverns - Alcove Next to Drowned Guards',
        'Underground Caverns - Bellow Stairway',
        'Underground Caverns - Bellow Wooden Bridge Left Item',
        'Underground Caverns - Bellow Wooden Bridge Right Item',
        'Underground Caverns - Bottom Underwater Item',
        'Underground Caverns - Bottom of Stairway',
        'Underground Caverns - Hidden Room Behind Waterfall',
        'Underground Caverns - Middle of Stairway Room',
        'Underground Caverns - Next to Castle Entrance Passage',
        'Underground Caverns - Red Vase on Ledge Next to Marble Gallery',
        'Underground Caverns - Room Behind Breakable Wall Close to Stairway',
        'Underground Caverns - Scylla item',
        'Underground Caverns - Top Left Room From Waterfall',
        'Underground Caverns - Top Underwater Item',
        'Underground Caverns - Underwater Stream',
        'Underground Caverns - Waterfall Bottom Item',
        'Underground Caverns - Waterfall Upper Item',
        'Underground Caverns - Wooden Stand Close to Stairway',
        'Underground Caverns Ice Area - After Ferryman',
        'Underground Caverns Ice Area - On Alcove',
        'Underground Caverns Ice Area - Underwater Item 1',
        'Underground Caverns Ice Area - Underwater Item 2',
        'Underground Caverns Ice Area - Underwater Item 3',
        'Underground Caverns Scylla Area - After Fight Item',
        'Underground Caverns Scylla Area - Left item',
        'Underground Caverns Scylla Area - Red Vase',
        'Underground Caverns Scylla Area - Right item',
        'Underground Caverns Succubus Side - Red Vase 1',
        'Underground Caverns Succubus Side - Red Vase 2',
        'Underground Caverns Succubus Side - Red Vase 3',
        'Underground Caverns Succubus Side - Red Vase 4',
        'Underground Caverns Succubus Side - Red Vase 5',
        'Underground Caverns Succubus Side - Red Vase 6',
        'Underground Caverns Succubus Side - Succubus item',
    },
}
