// Generated by tools/gen_location_data.py from the SotN AP world and the recomp's code. Do not edit by hand.
// Source: apworld/sotn_recomp
using System.Collections.Generic;
using RecompOne.Runtime.Context;
using RecompOne.Runtime.Memory;
using RecompOne.Runtime.Modding;

namespace SotnArchipelago;

public readonly record struct MusicSite(int Stage, uint Addr, byte Vanilla);

static class OptionData
{
    // enemy_stats: the HitDetection instruction Rom.py turns into 'li v0,3' (Faerie scroll owned), per stage
    public static readonly Dictionary<int, uint> FaerieForceSites = new()
    {
        [0x00] = 0x801C4274, // NO0
        [0x01] = 0x801C24DC, // NO1
        [0x02] = 0x801BFC1C, // LIB
        [0x03] = 0x801BC190, // CAT
        [0x04] = 0x801B9200, // NO2
        [0x05] = 0x8019E960, // CHI
        [0x06] = 0x801C6A74, // DAI
        [0x07] = 0x801B9BA8, // NP3
        [0x08] = 0x80191938, // CEN
        [0x09] = 0x801CB0DC, // NO4
        [0x0A] = 0x801B91C0, // ARE
        [0x0B] = 0x801AE11C, // TOP
        [0x0C] = 0x801B9FC0, // NZ0
        [0x0D] = 0x801AD1CC, // NZ1
        [0x0E] = 0x80188CD4, // WRP
        [0x12] = 0x80197A7C, // DRE
        [0x16] = 0x80197134, // BO7
        [0x17] = 0x8018DA5C, // MAR
        [0x18] = 0x801AA640, // BO6
        [0x19] = 0x801A76A0, // BO5
        [0x1A] = 0x801B74A8, // BO4
        [0x1B] = 0x801A71F0, // BO3
        [0x1C] = 0x801A815C, // BO2
        [0x1D] = 0x801A608C, // BO1
        [0x1E] = 0x801BCBC8, // BO0
        [0x1F] = 0x801B2214, // ST0
        [0x20] = 0x801B7E10, // RNO0
        [0x21] = 0x801AA788, // RNO1
        [0x22] = 0x801A364C, // RLIB
        [0x23] = 0x801B4A3C, // RCAT
        [0x24] = 0x801B77DC, // RNO2
        [0x25] = 0x8019B6E0, // RCHI
        [0x26] = 0x801B5118, // RDAI
        [0x27] = 0x801B499C, // RNO3
        [0x28] = 0x801A0F58, // RCEN
        [0x29] = 0x801CACD0, // RNO4
        [0x2A] = 0x801A762C, // RARE
        [0x2B] = 0x801A2FE0, // RTOP
        [0x2C] = 0x801AD6F0, // RNZ0
        [0x2D] = 0x801AD98C, // RNZ1
        [0x2E] = 0x8018AC54, // RWRP
        [0x36] = 0x8019A884, // RBO8
        [0x37] = 0x801969C0, // RBO7
        [0x38] = 0x801A5FA8, // RBO6
        [0x39] = 0x801B63DC, // RBO5
        [0x3A] = 0x801998F8, // RBO4
        [0x3B] = 0x80193C84, // RBO3
        [0x3C] = 0x801A256C, // RBO2
        [0x3D] = 0x80195C30, // RBO1
        [0x3E] = 0x8019AB50, // RBO0
        [0x41] = 0x801C2338, // NO3
    };

    // random_music: song request immediates ('ori vX,zero,0x3NN') in boss and cutscene code, with the
    // song they request on the disc
    public static readonly MusicSite[] MusicSites =
    [
        new(0x02, 0x801BB700, 0x1D), // LIB_BOSS
        new(0x02, 0x801BB7BC, 0x09), // LIB
        new(0x02, 0x801BB828, 0x09), // LIB
        new(0x0C, 0x801B4280, 0x1D), // NZ0_BOSS
        new(0x0C, 0x801B4350, 0x2E), // NZ0
        new(0x0C, 0x801B43CC, 0x2E), // NZ0
        new(0x0D, 0x801AA658, 0x1D), // NZ1_BOSS
        new(0x0D, 0x801AA718, 0x11), // NZ1
        new(0x0D, 0x801AA790, 0x11), // NZ1
        new(0x12, 0x801925BC, 0x30), // DRE
        new(0x16, 0x80196160, 0x19), // CHI
        new(0x19, 0x801A4500, 0x34), // BO5
        new(0x1B, 0x801A64B0, 0x0B), // NO4
        new(0x1B, 0x801A64F4, 0x0B), // NO4
        new(0x1B, 0x801A65FC, 0x1D), // BO3
        new(0x1B, 0x801A6690, 0x0B), // NO4
        new(0x1C, 0x801A4588, 0x23), // ARE
        new(0x1C, 0x801A6EA8, 0x1D), // BO2
        new(0x1D, 0x801A1AB8, 0x34), // BO1
        new(0x1D, 0x801A1AEC, 0x34), // BO1
        new(0x1D, 0x801A24E4, 0x07), // CAT
        new(0x1E, 0x801AD47C, 0x34), // BO0
        new(0x1E, 0x801AD4D8, 0x34), // BO0
        new(0x1E, 0x801AD4F8, 0x34), // BO0
        new(0x1E, 0x801AD56C, 0x34), // BO0
        new(0x1E, 0x801B8714, 0x17), // NO2
        new(0x28, 0x8019AD4C, 0x34), // RCEN_BOSS
        new(0x2D, 0x801ACA08, 0x1D), // RNZ1_BOSS
        new(0x2D, 0x801ACAAC, 0x38), // RNZ1
        new(0x2D, 0x801ACB24, 0x38), // RNZ1
        new(0x36, 0x80199648, 0x34), // RBO8
        new(0x36, 0x801996A8, 0x03), // RCAT
        new(0x36, 0x80199744, 0x03), // RCAT
        new(0x37, 0x80193F30, 0x1D), // RBO7
        new(0x39, 0x801B52A8, 0x1D), // RBO5
        new(0x3A, 0x80198894, 0x1D), // RBO4
        new(0x3A, 0x801988F4, 0x38), // RNO1
        new(0x3A, 0x80198990, 0x38), // RNO1
        new(0x3B, 0x80192BE0, 0x30), // RBO3
        new(0x3B, 0x80192C40, 0x01), // RDAI
        new(0x3B, 0x80192CDC, 0x01), // RDAI
        new(0x3C, 0x8019F5FC, 0x34), // RBO2
        new(0x3C, 0x8019F748, 0x19), // RCHI
        new(0x3D, 0x80194E20, 0x34), // RBO1
        new(0x3D, 0x80194E40, 0x34), // RBO1
        new(0x3D, 0x80194E98, 0x38), // RNZ0
        new(0x3D, 0x80194F28, 0x38), // RNZ0
        new(0x3E, 0x801945CC, 0x15), // RARE
        new(0x3E, 0x80194674, 0x15), // RARE
        new(0x41, 0x801B81C8, 0x0F), // NO3
        new(0x41, 0x801C027C, 0x0F), // NO3
    ];

    // Each stage's prize table (32 u16: what an enemy drops when not one of its items), for the extended
    // widescreen copy of HitDetection, which has the vanilla table built in (OptionHooks.SyncPrizeTable)
    public static readonly Dictionary<int, uint> PrizeTables = new()
    {
        [0x00] = 0x801814BC,
        [0x01] = 0x80181DDC,
        [0x02] = 0x80181FFC,
        [0x03] = 0x80181B18,
        [0x04] = 0x801813A8,
        [0x05] = 0x80180DA0,
        [0x06] = 0x801813F0,
        [0x07] = 0x801819CC,
        [0x08] = 0x80180B38,
        [0x09] = 0x80181D74,
        [0x0A] = 0x80181398,
        [0x0B] = 0x801811C8,
        [0x0C] = 0x801818F4,
        [0x0D] = 0x80181698,
        [0x0E] = 0x80180A10,
        [0x12] = 0x80180CFC,
        [0x16] = 0x80180C68,
        [0x18] = 0x80180A68,
        [0x19] = 0x801810E0,
        [0x1A] = 0x80180A30,
        [0x1B] = 0x80181478,
        [0x1C] = 0x80181044,
        [0x1D] = 0x801813C0,
        [0x1E] = 0x801817F8,
        [0x20] = 0x801813E8,
        [0x21] = 0x8018118C,
        [0x22] = 0x80180FB4,
        [0x23] = 0x801818E4,
        [0x24] = 0x801812C8,
        [0x25] = 0x80180C9C,
        [0x26] = 0x80181118,
        [0x27] = 0x801814CC,
        [0x28] = 0x80180E0C,
        [0x29] = 0x80181B28,
        [0x2A] = 0x80180E60,
        [0x2B] = 0x80180CB0,
        [0x2C] = 0x80181140,
        [0x2D] = 0x801816CC,
        [0x2E] = 0x80180A10,
        [0x36] = 0x80181B5C,
        [0x37] = 0x80180B28,
        [0x38] = 0x80180CC4,
        [0x39] = 0x80180ABC,
        [0x3A] = 0x80180BDC,
        [0x3B] = 0x80180AD0,
        [0x3C] = 0x80180FB0,
        [0x3D] = 0x80180D70,
        [0x3E] = 0x801811B0,
        [0x41] = 0x80182040,
    };
}

// Hooks for the option fixes in OptionHooks.cs, one pair per overlay function.
static class OptionHookSites
{
    [PreHook("no0", "HitDetection_no0")] static void Faerie_no0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("no0", "HitDetection_no0")] static void Faerie_no0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("no1", "HitDetection_no1")] static void Faerie_no1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("no1", "HitDetection_no1")] static void Faerie_no1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("lib", "HitDetection_lib")] static void Faerie_libIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("lib", "HitDetection_lib")] static void Faerie_libOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("cat", "HitDetection_cat")] static void Faerie_catIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("cat", "HitDetection_cat")] static void Faerie_catOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("no2", "HitDetection_no2")] static void Faerie_no2In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("no2", "HitDetection_no2")] static void Faerie_no2Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("chi", "HitDetection_chi")] static void Faerie_chiIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("chi", "HitDetection_chi")] static void Faerie_chiOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("dai", "HitDetection_dai")] static void Faerie_daiIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("dai", "HitDetection_dai")] static void Faerie_daiOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("np3", "HitDetection_np3")] static void Faerie_np3In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("np3", "HitDetection_np3")] static void Faerie_np3Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("cen", "HitDetection_cen")] static void Faerie_cenIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("cen", "HitDetection_cen")] static void Faerie_cenOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("no4", "HitDetection_no4")] static void Faerie_no4In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("no4", "HitDetection_no4")] static void Faerie_no4Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("are", "HitDetection_are")] static void Faerie_areIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("are", "HitDetection_are")] static void Faerie_areOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("top", "HitDetection_top")] static void Faerie_topIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("top", "HitDetection_top")] static void Faerie_topOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("nz0", "HitDetection_nz0")] static void Faerie_nz0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("nz0", "HitDetection_nz0")] static void Faerie_nz0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("nz1", "HitDetection_nz1")] static void Faerie_nz1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("nz1", "HitDetection_nz1")] static void Faerie_nz1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("wrp", "HitDetection_wrp")] static void Faerie_wrpIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("wrp", "HitDetection_wrp")] static void Faerie_wrpOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("dre", "HitDetection_dre")] static void Faerie_dreIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("dre", "HitDetection_dre")] static void Faerie_dreOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo7", "BO7_HitDetection")] static void Faerie_bo7In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo7", "BO7_HitDetection")] static void Faerie_bo7Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("mar", "HitDetection_mar")] static void Faerie_marIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("mar", "HitDetection_mar")] static void Faerie_marOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo6", "HitDetection_bo6")] static void Faerie_bo6In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo6", "HitDetection_bo6")] static void Faerie_bo6Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo5", "BO5_HitDetection")] static void Faerie_bo5In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo5", "BO5_HitDetection")] static void Faerie_bo5Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo4", "HitDetection_bo4")] static void Faerie_bo4In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo4", "HitDetection_bo4")] static void Faerie_bo4Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo3", "BO3_HitDetection")] static void Faerie_bo3In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo3", "BO3_HitDetection")] static void Faerie_bo3Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo2", "BO2_HitDetection")] static void Faerie_bo2In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo2", "BO2_HitDetection")] static void Faerie_bo2Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo1", "BO1_HitDetection")] static void Faerie_bo1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo1", "BO1_HitDetection")] static void Faerie_bo1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("bo0", "BO0_HitDetection")] static void Faerie_bo0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("bo0", "BO0_HitDetection")] static void Faerie_bo0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("st0", "ST0_HitDetection")] static void Faerie_st0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("st0", "ST0_HitDetection")] static void Faerie_st0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rno0", "RNO0_HitDetection")] static void Faerie_rno0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rno0", "RNO0_HitDetection")] static void Faerie_rno0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rno1", "RNO1_HitDetection")] static void Faerie_rno1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rno1", "RNO1_HitDetection")] static void Faerie_rno1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rlib", "RLIB_HitDetection")] static void Faerie_rlibIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rlib", "RLIB_HitDetection")] static void Faerie_rlibOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rcat", "HitDetection_rcat")] static void Faerie_rcatIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rcat", "HitDetection_rcat")] static void Faerie_rcatOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rno2", "RNO2_HitDetection")] static void Faerie_rno2In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rno2", "RNO2_HitDetection")] static void Faerie_rno2Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rchi", "RCHI_HitDetection")] static void Faerie_rchiIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rchi", "RCHI_HitDetection")] static void Faerie_rchiOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rdai", "RDAI_HitDetection")] static void Faerie_rdaiIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rdai", "RDAI_HitDetection")] static void Faerie_rdaiOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rno3", "RNO3_HitDetection")] static void Faerie_rno3In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rno3", "RNO3_HitDetection")] static void Faerie_rno3Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rcen", "RCEN_HitDetection")] static void Faerie_rcenIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rcen", "RCEN_HitDetection")] static void Faerie_rcenOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rno4", "RNO4_HitDetection")] static void Faerie_rno4In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rno4", "RNO4_HitDetection")] static void Faerie_rno4Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rare", "HitDetection_rare")] static void Faerie_rareIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rare", "HitDetection_rare")] static void Faerie_rareOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rtop", "HitDetection_rtop")] static void Faerie_rtopIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rtop", "HitDetection_rtop")] static void Faerie_rtopOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rnz0", "HitDetection_rnz0")] static void Faerie_rnz0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rnz0", "HitDetection_rnz0")] static void Faerie_rnz0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rnz1", "RNZ1_HitDetection")] static void Faerie_rnz1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rnz1", "RNZ1_HitDetection")] static void Faerie_rnz1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rwrp", "HitDetection_rwrp")] static void Faerie_rwrpIn(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rwrp", "HitDetection_rwrp")] static void Faerie_rwrpOut(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo8", "RBO8_HitDetection")] static void Faerie_rbo8In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo8", "RBO8_HitDetection")] static void Faerie_rbo8Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo7", "RBO7_HitDetection")] static void Faerie_rbo7In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo7", "RBO7_HitDetection")] static void Faerie_rbo7Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo6", "RBO6_HitDetection")] static void Faerie_rbo6In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo6", "RBO6_HitDetection")] static void Faerie_rbo6Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo5", "HitDetection_rbo5")] static void Faerie_rbo5In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo5", "HitDetection_rbo5")] static void Faerie_rbo5Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo4", "RBO4_HitDetection")] static void Faerie_rbo4In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo4", "RBO4_HitDetection")] static void Faerie_rbo4Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo3", "HitDetection_rbo3")] static void Faerie_rbo3In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo3", "HitDetection_rbo3")] static void Faerie_rbo3Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo2", "RBO2_HitDetection")] static void Faerie_rbo2In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo2", "RBO2_HitDetection")] static void Faerie_rbo2Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo1", "RBO1_HitDetection")] static void Faerie_rbo1In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo1", "RBO1_HitDetection")] static void Faerie_rbo1Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("rbo0", "HitDetection_rbo0")] static void Faerie_rbo0In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("rbo0", "HitDetection_rbo0")] static void Faerie_rbo0Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("no3", "HitDetection_no3")] static void Faerie_no3In(CpuContext c, IMemory m) => OptionHooks.FaerieIn(m);
    [PostHook("no3", "HitDetection_no3")] static void Faerie_no3Out(CpuContext c, IMemory m) => OptionHooks.FaerieOut(m);
    [PreHook("no1", "EntityEquipItemDrop_no1")] static void Drop_no1(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("chi", "EntityEquipItemDrop_chi")] static void Drop_chi(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("np3", "EntityEquipItemDrop_np3")] static void Drop_np3(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("top", "EntityEquipItemDrop_top")] static void Drop_top(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("nz1", "EntityEquipItemDrop_nz1")] static void Drop_nz1(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("rno1", "RNO1_EntityEquipItemDrop")] static void Drop_rno1(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("rno3", "RNO3_EntityEquipItemDrop")] static void Drop_rno3(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("rnz1", "func_801B26EC_rnz1")] static void Drop_rnz1(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("no3", "EntityEquipItemDrop_no3")] static void Drop_no3(CpuContext c, IMemory m) => DespawnDrops.Keep(c, m);
    [PreHook("bo0", "func_801AD338")] static void Music_bo0_func_801AD338In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo0", "func_801AD338")] static void Music_bo0_func_801AD338Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo0", "func_801B7CC8")] static void Music_bo0_func_801B7CC8In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo0", "func_801B7CC8")] static void Music_bo0_func_801B7CC8Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo1", "func_801A1878")] static void Music_bo1_func_801A1878In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo1", "func_801A1878")] static void Music_bo1_func_801A1878Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo2", "func_801A3E04")] static void Music_bo2_func_801A3E04In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo2", "func_801A3E04")] static void Music_bo2_func_801A3E04Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo2", "func_801A5DCC")] static void Music_bo2_func_801A5DCCIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo2", "func_801A5DCC")] static void Music_bo2_func_801A5DCCOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo3", "func_801A6370")] static void Music_bo3_func_801A6370In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo3", "func_801A6370")] static void Music_bo3_func_801A6370Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo3", "func_801A6568_bo3")] static void Music_bo3_func_801A6568_bo3In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo3", "func_801A6568_bo3")] static void Music_bo3_func_801A6568_bo3Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo5", "func_801A4494")] static void Music_bo5_func_801A4494In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo5", "func_801A4494")] static void Music_bo5_func_801A4494Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("bo7", "func_80195C50")] static void Music_bo7_func_80195C50In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("bo7", "func_80195C50")] static void Music_bo7_func_80195C50Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("dre", "EntitySuccubus")] static void Music_dre_EntitySuccubusIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("dre", "EntitySuccubus")] static void Music_dre_EntitySuccubusOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("lib", "func_us_801BB53C")] static void Music_lib_func_us_801BB53CIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("lib", "func_us_801BB53C")] static void Music_lib_func_us_801BB53COut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("no3", "EntityBackgroundLightning_no3")] static void Music_no3_EntityBackgroundLightning_no3In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("no3", "EntityBackgroundLightning_no3")] static void Music_no3_EntityBackgroundLightning_no3Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("no3", "EntityDeathCutsceneManager")] static void Music_no3_EntityDeathCutsceneManagerIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("no3", "EntityDeathCutsceneManager")] static void Music_no3_EntityDeathCutsceneManagerOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("nz0", "EntityBossFightManager")] static void Music_nz0_EntityBossFightManagerIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("nz0", "EntityBossFightManager")] static void Music_nz0_EntityBossFightManagerOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("nz1", "EntityBossDoorTrigger")] static void Music_nz1_EntityBossDoorTriggerIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("nz1", "EntityBossDoorTrigger")] static void Music_nz1_EntityBossDoorTriggerOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo0", "RBO0_EntityBoss")] static void Music_rbo0_RBO0_EntityBossIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo0", "RBO0_EntityBoss")] static void Music_rbo0_RBO0_EntityBossOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo1", "func_80194C50")] static void Music_rbo1_func_80194C50In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo1", "func_80194C50")] static void Music_rbo1_func_80194C50Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo2", "func_8019F4AC")] static void Music_rbo2_func_8019F4ACIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo2", "func_8019F4AC")] static void Music_rbo2_func_8019F4ACOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo3", "func_us_80192B38")] static void Music_rbo3_func_us_80192B38In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo3", "func_us_80192B38")] static void Music_rbo3_func_us_80192B38Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo4", "func_8019879C")] static void Music_rbo4_func_8019879CIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo4", "func_8019879C")] static void Music_rbo4_func_8019879COut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo5", "EntityUnkId1E")] static void Music_rbo5_EntityUnkId1EIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo5", "EntityUnkId1E")] static void Music_rbo5_EntityUnkId1EOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo7", "func_80193E88")] static void Music_rbo7_func_80193E88In(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo7", "func_80193E88")] static void Music_rbo7_func_80193E88Out(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rbo8", "func_8019953C")] static void Music_rbo8_func_8019953CIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rbo8", "func_8019953C")] static void Music_rbo8_func_8019953COut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rcen", "func_8019AAFC")] static void Music_rcen_func_8019AAFCIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rcen", "func_8019AAFC")] static void Music_rcen_func_8019AAFCOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
    [PreHook("rnz1", "func_801AC7CC")] static void Music_rnz1_func_801AC7CCIn(CpuContext c, IMemory m) => OptionHooks.MusicIn(m);
    [PostHook("rnz1", "func_801AC7CC")] static void Music_rnz1_func_801AC7CCOut(CpuContext c, IMemory m) => OptionHooks.MusicOut(m);
}
