// Generated by tools/gen_location_data.py from the SotN AP world. Do not edit by hand.
// Source: apworld/sotn
using System.Collections.Generic;

namespace SotnArchipelago;

static class SpecialData
{
    // AP zone key -> (g_StageId, item table offset, boss rewards offset) in the stage file; -1 = none
    public static readonly Dictionary<string, (int Stage, int Items, int Rewards)> Zones = new()
    {
        ["ST0"] = (0x1F, 0xa60, -1),
        ["ARE"] = (0x0A, 0xfe8, -1),
        ["CAT"] = (0x03, 0x174c, -1),
        ["CEN"] = (0x08, -1, -1),
        ["CHI"] = (0x05, 0x9e4, -1),
        ["DAI"] = (0x06, 0xec0, -1),
        ["DRE"] = (0x12, 0x1928, -1),
        ["LIB"] = (0x02, 0x1a90, -1),
        ["NO0"] = (0x00, 0x1100, -1),
        ["NO1"] = (0x01, 0x1a2c, -1),
        ["NO2"] = (0x04, 0xfec, -1),
        ["NO3"] = (0x41, 0x1c8c, -1),
        ["NP3"] = (0x07, 0x1618, -1),
        ["NO4"] = (0x09, 0x1928, -1),
        ["NZ0"] = (0x0C, 0x13b0, -1),
        ["NZ1"] = (0x0D, 0x111c, -1),
        ["TOP"] = (0x0B, 0xd10, -1),
        ["WRP"] = (0x0E, -1, -1),
        ["RARE"] = (0x2A, 0xa3c, -1),
        ["RCAT"] = (0x23, 0x13c8, -1),
        ["RCEN"] = (0x28, -1, -1),
        ["RCHI"] = (0x25, 0x7cc, -1),
        ["RDAI"] = (0x26, 0xd2c, -1),
        ["RLIB"] = (0x22, 0xbc8, -1),
        ["RNO0"] = (0x20, 0xf8c, -1),
        ["RNO1"] = (0x21, 0xae4, -1),
        ["RNO2"] = (0x24, 0xd40, -1),
        ["RNO3"] = (0x27, 0xf10, -1),
        ["RNO4"] = (0x29, 0x1620, -1),
        ["RNZ0"] = (0x2C, 0xcc8, -1),
        ["RNZ1"] = (0x2D, 0xec8, 0x2570),
        ["RTOP"] = (0x2B, 0x7c8, -1),
        ["RWRP"] = (0x2E, -1, -1),
        ["BO0"] = (0x1E, -1, 0x24d4),
        ["BO1"] = (0x1D, -1, 0x1b98),
        ["BO2"] = (0x1C, -1, 0x181c),
        ["BO3"] = (0x1B, 0x108c, 0x1c60),
        ["BO4"] = (0x1A, -1, 0x42b0),
        ["BO5"] = (0x19, -1, 0x18b8),
        ["BO6"] = (0x18, -1, 0x2f90),
        ["BO7"] = (0x16, -1, 0x1440),
        ["RBO0"] = (0x3E, -1, 0x1988),
        ["RBO1"] = (0x3D, -1, 0x1550),
        ["RBO2"] = (0x3C, -1, 0x1788),
        ["RBO3"] = (0x3B, -1, 0x12a8),
        ["RBO4"] = (0x3A, -1, 0x13b4),
        ["RBO5"] = (0x39, -1, 0x4348),
        ["RBO6"] = (0x38, -1, -1),
        ["RBO7"] = (0x37, -1, 0x1300),
        ["RBO8"] = (0x36, -1, 0x2334),
    };

    // Fixed patch addresses Rom.py writes as raw disc offsets
    public static readonly StageAddr RingOfVladEntityId = new(0x2D, 0x801AC840);
    public static readonly StageAddr RingOfVladUpdateLow = new(0x2D, 0x801AC84C);
    public static readonly StageAddr RingOfVladIndex = new(0x2D, 0x801AC85C);
    public static readonly StageAddr JewelRelicOffset = new(0x02, 0x801B2B08);
    public static readonly StageAddr JewelName = new(0x02, 0x801AD088);

    // Per location: the instructions Rom.py overwrites to stop a relic from loading ("erase")
    public static readonly Dictionary<long, (StageAddr At, uint Instruction)[]> Erase = new()
    {
        [85] = [(new(0x08, 0x8018FE98), 0x08063FF6)], // Marble Gallery - Item Given by Maria
        [240] = [(new(0x3C, 0x8019F728), 0x34020000)], // Cave - Death Item
        [257] = [(new(0x3B, 0x80192CBC), 0x34020000)], // Medusa Kill Item
        [288] = [(new(0x3A, 0x80198970), 0x34020000)], // Creature Kill Item
        [301] = [(new(0x37, 0x8019400C), 0x34020000)], // Death Wing's Lair - Akmodan II Item
        [366] = [(new(0x2D, 0x801ACB0C), 0x34020000), (new(0x2D, 0x801AC848), 0x34020000), (new(0x2D, 0x801AC84C), 0x00000000)], // Reverse Clock Tower - Darkwing Bat Item
        [386] = [(new(0x3E, 0x8019465C), 0x34020000)], // Reverse Colosseum - Trio item
    };
}
