// Generated by tools/gen_location_data.py from the SotN AP world. Do not edit by hand.
// Source: ref/ap-world/apworld-b08161/sotn
using System.Collections.Generic;

namespace SotnArchipelago;

static class ZoneData
{
    // g_StageId -> zone name as the AP world and its tracker know it
    public static readonly Dictionary<int, string> Names = new()
    {
        [0x00] = "Marble Gallery", // NO0
        [0x01] = "Outer Wall", // NO1
        [0x02] = "Long Library", // LIB
        [0x03] = "Catacombs", // CAT
        [0x04] = "Olrox's Quarters", // NO2
        [0x05] = "Abandoned Mine", // CHI
        [0x06] = "Royal Chapel", // DAI
        [0x07] = "Castle Entrance (after visiting Alchemy Laboratory)", // NP3
        [0x08] = "Center Cube", // CEN
        [0x09] = "Underground Caverns", // NO4
        [0x0A] = "Colosseum", // ARE
        [0x0B] = "Castle Keep", // TOP
        [0x0C] = "Alchemy Laboratory", // NZ0
        [0x0D] = "Clock Tower", // NZ1
        [0x0E] = "Warp rooms", // WRP
        [0x12] = "Nightmare", // DRE
        [0x16] = "Cerberus", // BO7
        [0x18] = "Richter", // BO6
        [0x19] = "Hippogryph", // BO5
        [0x1A] = "Doppleganger10", // BO4
        [0x1B] = "Scylla", // BO3
        [0x1C] = "Werewolf & Minotaur", // BO2
        [0x1D] = "Granfaloon", // BO1
        [0x1E] = "Olrox", // BO0
        [0x1F] = "Final Stage: Bloodlines", // ST0
        [0x20] = "Black Marble Gallery", // RNO0
        [0x21] = "Reverse Outer Wall", // RNO1
        [0x22] = "Forbidden Library", // RLIB
        [0x23] = "Floating Catacombs", // RCAT
        [0x24] = "Death Wing's Lair", // RNO2
        [0x25] = "Cave", // RCHI
        [0x26] = "Anti-Chapel", // RDAI
        [0x27] = "Reverse Entrance", // RNO3
        [0x28] = "Reverse Center Cube", // RCEN
        [0x29] = "Reverse Caverns", // RNO4
        [0x2A] = "Reverse Colosseum", // RARE
        [0x2B] = "Reverse Castle Keep", // RTOP
        [0x2C] = "Necromancy Laboratory", // RNZ0
        [0x2D] = "Reverse Clock Tower", // RNZ1
        [0x2E] = "Reverse Warp rooms", // RWRP
        [0x36] = "Galamoth", // RBO8
        [0x37] = "Akmodan II", // RBO7
        [0x38] = "Shaft/Dracula", // RBO6
        [0x39] = "Doppleganger40", // RBO5
        [0x3A] = "Creature", // RBO4
        [0x3B] = "Medusa", // RBO3
        [0x3C] = "Death", // RBO2
        [0x3D] = "Beezlebub", // RBO1
        [0x3E] = "Trio", // RBO0
        [0x41] = "Castle Entrance", // NO3
    };
}
